CREATE TABLE IF NOT EXISTS documents (
    id BIGSERIAL PRIMARY KEY,  
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    title TEXT NOT NULL,
    subject TEXT NOT NULL,
    summary TEXT NOT NULL,
    filename TEXT NOT NULL,
    majorver SMALLINT NOT NULL DEFAULT 0,
    minorver SMALLINT NOT NULL DEFAULT 0,
    author BIGINT NOT NULL REFERENCES users (id)
);